# -*- encoding: utf-8 -*-
import distutils.core

"""
Django settings for jab project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'tm3%=#*^60e*5&ykgu8z5&xrc-dee@-!0ozgp*(o8==zg$qdq*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
PORT_LOCALHOST = ':8000'
NAME_HOST = 'jab.desa'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bases',
    'perfil',
    'usuario',
    'configuracion',
    'documento',
    'clienteproveedor',
    'seguridad',
]

MIDDLEWARE = [
    'jab.middleware.middleware.multidb_middleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'jab.middleware.middleware_menu.menu_middleware_items',
    'jab.middleware.menu_middleware.menu_middleware',
    'jab.middleware.middleware_session.middleware_active_session',

]

ROOT_URLCONF = 'jab.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jab.wsgi.application'

DATABASE_ROUTERS = ['jab.routers.Cableado']
# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {

    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'jab_bases',
        'USER': 'jab',
        'PASSWORD': 'nEgWJvX";00mCFJ~mAKL',
        'HOST': 'localhost',
        'PORT': '5432',
    },
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/
LANGUAGE_CODE = 'es'
LOCALE_LANG = 'es_CL.UTF-8'
TIME_ZONE = 'America/Santiago'

USE_I18N = True
# USE_L10N = True

SHORT_DATETIME_FORMAT = 'd/m/Y H:M:S.f'
SHORT_DATE_FORMAT = 'd/m/Y'
DATETIME_FORMAT = 'd/m/Y H:M:S.f'
DATE_FORMAT = 'd/m/Y'
DATE_INPUT_FORMATS = ['%d/%m/%Y', '%Y-%m-%d']
DATETIME_INPUT_FORMATS = ['%d/%m/%Y %H:%M:%S.%f', '%d/%m/%Y %H:%M:%S', '%Y-%m-%d %H:%M:%S.%f', '%Y-%m-%d %H:%M:%S']
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
IS_WINDOWS = ''

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    os.path.join(BASE_DIR, "templates"),
]

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')
BASE_COMMAND = IS_WINDOWS + '/home/osvaldo/jab/jab/'
RUTA_PDF = BASE_COMMAND + 'templates/docpdf/'

PYTHON_COMMAND = 'python'  # en el caso de linux es python3

# Tiempo de vida de la sesion en segundos
SESSION_COOKIE_AGE = 10800

# Para que expire la sesion al cerrar el navegador. Por defecto está a False
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

WKHTMLTOPDF_BIN_PATH = '/usr/local/bin/wkhtmltopdf'

UPLOAD_DIR_FOTO = 'static/'
UPLOAD_DIR = 'static/'
